#!/bin/bash -e

# TODO support arg parsing properly
CWLDEF=$3
INPUTS=$4
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

WFNAME=${CWLDEF%.cwl}
WFNAME=${WFNAME##*/}

dx login --token $DXTOKEN --noproject > /dev/null 2>&1
dx select $DXPROJ > /dev/null 2>&1

dx cd /  > /dev/null 2>&1

# Only workflows for the moment
$DIR/dx-cwl compile-workflow $CWLDEF --token $DXTOKEN --project $DXPROJ #> /dev/null 2>&1

$DIR/dx-cwl run-workflow dx-cwl-run/$WFNAME/$WFNAME $INPUTS --token $DXTOKEN --project $DXPROJ --wait
